import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // { type: "autogenerated", dirName: "." },
    {
      type: "doc",
      id: "intro", // This points to intro.md
      label: "Introduction",
    },
    {
      type: "category",
      label: "Quickstart",
      items: [{ type: "autogenerated", dirName: "quickstart" }],
    },
    {
      type: "category",
      label: "Platform Overview",
      items: [{ type: "autogenerated", dirName: "platform-overview" }],
    },
    {
      type: "category",
      label: "Containers",
      items: [{ type: "autogenerated", dirName: "containers" }],
    },
    {
      type: "category",
      label: "Environment Management",
      items: [{ type: "autogenerated", dirName: "environment-management" }],
    },
    {
      type: "category",
      label: "Deployment",
      items: [{ type: "autogenerated", dirName: "deployment" }],
    },
    {
      type: "category",
      label: "Application Settings",
      items: [{ type: "autogenerated", dirName: "application-settings" }],
    },
    {
      type: "category",
      label: "Development Tools",
      items: [
        {
          type: "category",
          label: "SSH",
          items: [{ type: "autogenerated", dirName: "development-tools/ssh" }],
        },
        {
          type: "category",
          label: "API & CLI",
          items: [
            "development-tools/api-and-cli/api-overview",
            {
              type: "link",
              label: "API Methods",
              href: "https://docs.jelastic.com/api/",
            },
            {
              type: "category",
              label: "Platform CLI",
              items: [
                {
                  type: "autogenerated",
                  dirName: "development-tools/api-and-cli/platform-cli",
                },
              ],
            },
            "development-tools/api-and-cli/createenv-params",
          ],
        },
        {
          type: "category",
          label: "Cloud Scripting & JPS",
          items: [
            {
              type: "link",
              label: "Cloud Scripting",
              href: "https://docs.cloudscripting.com/",
            },
            "development-tools/cloud-scripting-and-jps/jps-overview",
            "development-tools/cloud-scripting-and-jps/application-manifest",
            "development-tools/cloud-scripting-and-jps/marketplace",
          ],
        },
        "development-tools/ftpftps-support",
        {
          type: "category",
          label: "WebSockets",
          items: [
            {
              type: "autogenerated",
              dirName: "development-tools/websockets",
            },
          ],
        },
        {
          type: "category",
          label: "Mailings",
          link: {
            type: "generated-index",
            slug: "/mailings",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "development-tools/mailings",
            },
          ],
        },
        "development-tools/remote-access-via-webdav",
      ],
    },
    {
      type: "category",
      label: "Java",
      // items: [{ type: "autogenerated", dirName: "java" }],
      items: [
        "java/java-dev-center",
        "java/java-versions",
        {
          type: "category",
          label: "Java App Servers",
          items: [
            {
              type: "category",
              label: "Tomcat and TomEE",
              items: [
                "java/java-app-servers/tomcat-and-tomee/tomcat-server",
                "java/java-app-servers/tomcat-and-tomee/tomee-server",
                {
                  type: "ref",
                  label: "Tomcat and TomEE Variables",
                  id: "environment-management/environment-variables/custom-environment-variables",
                },
                "java/java-app-servers/tomcat-and-tomee/tomcat-clustering",
                "java/java-app-servers/tomcat-and-tomee/tomcat-security",
                {
                  type: "ref",
                  label: "Multiple Domains for Tomcat",
                  id: "application-settings/domain-name-management/multiple-domains-for-tomcat",
                },
              ],
            },
            {
              type: "category",
              label: "Jetty",
              items: [
                "java/java-app-servers/jetty/jetty-server",
                {
                  type: "ref",
                  label: "Jetty Variables",
                  id: "environment-management/environment-variables/custom-environment-variables",
                },
              ],
            },
            {
              type: "category",
              label: "GlassFish",
              items: [
                "java/java-app-servers/glassfish/glassfish-server",
                {
                  type: "ref",
                  label: "GlassFish Environment Variables",
                  id: "environment-management/environment-variables/custom-environment-variables",
                },
                "java/java-app-servers/glassfish/glassfish-clustering",
                {
                  type: "ref",
                  label: "Multiple Domains for GlassFish",
                  id: "application-settings/domain-name-management/multiple-domains-for-glassfish",
                },
              ],
            },
            "java/java-app-servers/payara",
            {
              type: "category",
              label: "WildFly",
              items: [
                "java/java-app-servers/wildfly/wildfly-server",
                "java/java-app-servers/wildfly/wildfly-managed-domain",
                "java/java-app-servers/wildfly/building-wildfly-docker-image",
              ],
            },
            "java/java-app-servers/spring-boot",
          ],
        },
        "java/java-app-server-configuration",
        "java/java-garbage-collector",
        {
          type: "category",
          label: "Maven Build Node",
          items: [{ type: "autogenerated", dirName: "java/build-node" }],
        },
        {
          type: "category",
          label: "Java Apps Specifications",
          items: [
            { type: "autogenerated", dirName: "java/java-apps-specifications" },
          ],
        },
        "java/java-tutorials",
      ],
    },
    {
      type: "category",
      label: "PHP",
      // items: [{ type: "autogenerated", dirName: "php" }],
      items: [
        "php/php-dev-center",
        "php/php-versions",
        {
          type: "category",
          label: "PHP App Servers",
          items: [{ type: "autogenerated", dirName: "php/php-app-servers" }],
        },
        "php/php-app-server-configuration",
        "php/zdt-deployment-for-php",
        {
          type: "category",
          label: "PHP Apps Specifications",
          items: [
            { type: "autogenerated", dirName: "php/php-apps-specifications" },
          ],
        },
        "php/php.ini-security-settings",
        "php/composer-dependency-manager",
        {
          type: "ref",
          id: "memcached/php-sessions-in-memcached",
          label: "PHP Sessions Clustering",
        },
        "php/php-tutorials",
      ],
    },
    {
      type: "category",
      label: "Node.js",
      items: [{ type: "autogenerated", dirName: "node.js" }],
    },
    {
      type: "category",
      label: "Ruby",
      items: [{ type: "autogenerated", dirName: "ruby" }],
    },
    {
      type: "category",
      label: "Python",
      items: [{ type: "autogenerated", dirName: "python" }],
    },
    {
      type: "category",
      label: "Go Lang",
      items: [{ type: "autogenerated", dirName: "go-lang" }],
    },
    {
      type: "category",
      label: "Windows and .NET",
      items: [{ type: "autogenerated", dirName: "windows-and-.net" }],
    },
    {
      type: "category",
      label: "Databases",
      items: [
        {
          type: "category",
          label: "Database Hosting",
          items: [
            { type: "autogenerated", dirName: "databases/database-hosting" },
          ],
        },
        {
          type: "category",
          label: "MySQL/MariaDB/Percona",
          items: [
            {
              type: "autogenerated",
              dirName: "databases/mysqlmariadbpercona",
            },
          ],
        },
        {
          type: "category",
          label: "PostgreSQL",
          items: [
            {
              type: "category",
              label: "Connection to Applications",
              items: [
                {
                  type: "autogenerated",
                  dirName: "databases/postgresql/connection-to-applications",
                },
              ],
            },
            {
              type: "category",
              label: "High Availability (Cluster)",
              items: [
                {
                  type: "autogenerated",
                  dirName: "databases/postgresql/high-availability-(cluster)",
                },
              ],
            },
            {
              type: "ref",
              label: "Backup/Restore Add-On",
              id: "databases/mysqlmariadbpercona/backuprestore-add-on",
            },
            "databases/postgresql/encryption-in-transit-add-on",
            "databases/postgresql/remote-access-to-postgresql",
            "databases/postgresql/dump-importexport-to-postgresql",
            "databases/postgresql/postgis-extension",
            "databases/postgresql/hasura-graphql-installation",
          ],
        },
        {
          type: "category",
          label: "MongoDB",
          items: [{ type: "autogenerated", dirName: "databases/mongodb" }],
        },
        {
          type: "category",
          label: "Redis",
          items: [
            "databases/redis/redis-overview",
            {
              type: "category",
              label: "High Availability (Cluster)",
              items: [
                {
                  type: "autogenerated",
                  dirName: "databases/redis/high-availability-(cluster)",
                },
              ],
            },
            {
              type: "ref",
              label: "Backup/Restore Add-On",
              id: "databases/mysqlmariadbpercona/backuprestore-add-on",
            },
            "databases/redis/encryption-in-transit-add-on",
            {
              type: "ref",
              label: "Diaspora* Tutorial",
              id: "ruby/ruby-tutorials/diaspora",
            },
          ],
        },
        {
          type: "category",
          label: "Couchbase",
          items: [{ type: "autogenerated", dirName: "databases/couchbase" }],
        },
        {
          type: "category",
          label: "OpenSearch",
          items: [{ type: "autogenerated", dirName: "databases/opensearch" }],
        },
      ],
    },
    {
      type: "category",
      label: "Load Balancers",
      items: [{ type: "autogenerated", dirName: "load-balancers" }],
    },
    {
      type: "category",
      label: "Kubernetes Hosting",
      items: [{ type: "autogenerated", dirName: "kubernetes-hosting" }],
    },
    {
      type: "category",
      label: "Wordpress as a Service",
      items: [{ type: "autogenerated", dirName: "wordpress-as-a-service" }],
    },
    {
      type: "category",
      label: "Elastic VPS",
      // items: [{ type: "autogenerated", dirName: "elastic-vps" }],
      items: [
        {
          type: "category",
          label: "Elastic VPS Overview",
          items: [
            {
              type: "autogenerated",
              dirName: "elastic-vps/elastic-vps-overview",
            },
          ],
        },
        {
          type: "category",
          label: "Elastic VPS Management",
          items: [
            "elastic-vps/elastic-vps-management/vps-configuration",
            "elastic-vps/elastic-vps-management/linux-vps-access-via-ssh-gate",
            "elastic-vps/elastic-vps-management/linux-vps-access-via-public-ip",
            {
              type: "ref",
              label: "Windows VPS Access via RDP",

              id: "windows-and-.net/windows-rd-access",
            },
          ],
        },
        {
          type: "category",
          label: "Elastic VPS Use Cases",
          items: [
            {
              type: "autogenerated",
              dirName: "elastic-vps/linux-vps-use-cases",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Data Storage and Containers",
      items: [{ type: "autogenerated", dirName: "data-storage-container" }],
    },
    {
      type: "category",
      label: "Memcached",
      items: [{ type: "autogenerated", dirName: "memcached" }],
    },
    {
      type: "category",
      label: "Account and Pricing",
      items: [{ type: "autogenerated", dirName: "account-and-pricing" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
