name: Deploy Docusaurus Site

on:
  workflow_run:
    workflows: ["Test deployment"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Virtuozzo
        run: |
          rsync -e "ssh -i ~/.ssh/id_rsa -p 3022" -avz --delete ./build/ 49879-5737@gate.infra.dewacloud.com:/data
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
