name: Run DocSearch Scraper

on:
  # Runs on manual trigger
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run DocSearch Scraper
        run: |
          docker run --rm \
            -e "TYPESENSE_API_KEY=${{ secrets.TYPESENSE_API_KEY }}" \
            -e "TYPESENSE_HOST=${{ vars.TYPESENSE_HOST }}" \
            -e "TYPESENSE_PORT=443" \
            -e "TYPESENSE_PROTOCOL=https" \
            -e "CONFIG=$(cat docsearch.config.json | jq -r tostring)" \
            --dns=8.8.8.8 --dns=8.8.4.4 \
            typesense/docsearch-scraper:0.9.1
